# GitHub Actions workflow to run backend unit tests automatically
# Triggered on push or pull request to any file under the 'backend/' directory
# This sets up a virtual environment in GitHub's cloud runner, installs dependencies, and runs pytest

name: Run Backend Tests

on: # Trigger tests when files in the backend folder change on push/pull
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest #GitHub runs tests on a cloud-hosted Ubuntu VM (does not affect local machine)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Clones the repository into the runner so tests have access to code

      - name: Set up Python
        uses: actions/setup-python@v5 # Installs the specified Python version
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        # Creates a virtual environment, installs project dependencies and test tools
        run: |
          python -m venv venv
          ./venv/bin/pip install -r ../requirements.txt
          ./venv/bin/pip install pytest httpx pytest-asyncio

      - name: Run tests with pytest
        working-directory: backend
        run: |
          ./venv/bin/python -m pytest

